# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NoteWithFireStore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_modular_headers!
  use_frameworks!

  # Pods for NoteWithFireStore
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  
  target 'NoteWithFireStoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NoteWithFireStoreUITests' do
    # Pods for testing
  end

end
