# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NoteWithFireStore' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  use_modular_headers!

  # Pods for NoteWithFireStore
  pod 'BoringSSL-GRPC'
  pod 'Firebase/Performance'
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'SCLAlertView'
  pod 'BoringSSL-GRPC', '= 0.0.3', :modular_headers => false
  pod 'gRPC-Core', '= 1.21.0', :modular_headers => false


  target 'NoteWithFireStoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NoteWithFireStoreUITests' do
    # Pods for testing
  end

end

